### ISSUE TITLE
Short Password Causes Crash in Account Creation

### ISSUE THREAD

**Issue by Adept7777** [azb/SE195A_SeniorProject#16]
Found while testing around with application preparing for the demo, if too short of a password is used in the signup page it causes a crash when clicking on the button, and no account is created.

May just be a restriction from Firebase on the minimum required length for passwords, and Firebase returns some exception if that length is not met, and we might not be handling that so it causes a crash?

Something to look into later.

**Comment by kmbeaulieu** [comment]
now it just says auth failed. will fix this to have an error message
